### ISSUE TITLE
Object cell reader should return null on empty string

### ISSUE THREAD

**Issue by eharik** [arnaudroger/SimpleFlatMapper#84] opened 2015-01-27 23:40 UTC
When parsing rows that have adjacent commas, indicating a lack of value, the parser throws an error.

Note that I'm running this in Scala so not sure if that's impacting anything.

```
test.csv
my_field,second_field
,,
```

```java
class TestClass(var myField: String, var secondField)

val it = CsvParser.mapTo(classOf[TestClass]).iterate(reader)
while(it.hasNext) { println(it.next.myField) }
```

```java
java.lang.Exception: org.sfm.map.MappingException: Error mapping field org.sfm.csv.CsvColumnKey@3978a417 : null
  at io.oseberg.service.bpoocc.CompletionArcgateMasterFileV1ServiceSfm.test(CompletionArcgateMasterFileV1ServiceSfm.scala:41)
  ... 43 elided
Caused by: org.sfm.map.MappingException: Error mapping field org.sfm.csv.CsvColumnKey@3978a417 : null
  at org.sfm.map.impl.RethrowFieldMapperErrorHandler.errorMappingField(RethrowFieldMapperErrorHandler.java:11)
  at org.sfm.csv.impl.CsvMapperCellConsumer.newCellForSetter(CsvMapperCellConsumer.java:162)
  at org.sfm.csv.impl.CsvMapperCellConsumer.newCell(CsvMapperCellConsumer.java:191)
  at org.sfm.csv.impl.CsvMapperCellConsumer.newCell(CsvMapperCellConsumer.java:177)
  at org.sfm.csv.parser.AbstractCsvCharConsumer.newCell(AbstractCsvCharConsumer.java:101)
  at org.sfm.csv.parser.AbstractCsvCharConsumer.newCellIfNotInQuote(AbstractCsvCharConsumer.java:45)
  at org.sfm.csv.parser.StandardCsvCharConsumer.nextRow(StandardCsvCharConsumer.java:41)
  at org.sfm.csv.CsvReader.parseRow(CsvReader.java:70)
  at org.sfm.csv.impl.CsvMapperIterator.fetch(CsvMapperIterator.java:39)
  at org.sfm.csv.impl.CsvMapperIterator.hasNext(CsvMapperIterator.java:31)
```

**Comment by arnaudroger** [comment] 2015-01-28 07:44
Thanks for the report, I'll check that out. I have not test it for scala so it might be link to the types.

**Comment by arnaudroger** [comment] 2015-01-28 07:58
did a quick test there and cannot reproduce on a simple java object, would you have the full stack trace with the line at which the npe was thrown? 
Also do you know what type is secondField resolved too?
I'll try to get a scala test setup but it will take some time.

**Comment by arnaudroger** [comment] 2015-01-28 08:27
I try the following code 

```scala 

import java.io.StringReader

import org.sfm.csv.CsvParser

object TestIssue84 {

  class TestClass(var myField: String, var secondField: String) 

  def main(args: Array[String]) {


    val it = CsvParser.mapTo(classOf[TestClass]).iterate(new StringReader("my_field,second_field\n,,"))
    while(it.hasNext) { println(it.next.myField); println("X") }

  }
}
```

and it works fine. I'm not an expert in scala it seems you I needed to specify the type for second field. If I put Any I get a error as expected. I used the intellij plugin with the last scala jars

**Comment by arnaudroger** [comment] 2015-01-28 08:30
see https://github.com/arnaudroger/SimpleFlatMapper/blob/master/src/test/scala/TestIssue84.scala

**Comment by arnaudroger** [comment] 2015-01-28 08:31
just to check which version did you use?

**Comment by arnaudroger** [comment] 2015-01-28 16:51
I think I reproduced it in 1.2.0 if that's the case the it's fixed in 1.3, can you confirm the version you are using?

**Comment by eharik** [comment] 2015-01-28 17:59
Thanks for looking into this.  The example above was typed free hand and the stack trace was taken from the actual error I was having in my application.  In the application the type was defined for the second field in the class.

I pushed some test code up to [my github](https://github.com/eharik/sfm-issue84) with the settings I am using.  After looking into this a bit further I believe the issue was that I was using `java.sql.Date` rather than `java.util.Date`.  (I would love if you supported joda time and I see you already have that listed as an improvement.) 

Now that I've switched to `java.util.Date` I'm having an issue parsing empty dates.  Specifically:

```
[error] (run-main-9) org.sfm.map.MappingException: Error mapping field org.sfm.csv.CsvColumnKey@4d0e8491 : Unparseable date: ""
org.sfm.map.MappingException: Error mapping field org.sfm.csv.CsvColumnKey@4d0e8491 : Unparseable date: ""
	at org.sfm.map.impl.RethrowFieldMapperErrorHandler.errorMappingField(RethrowFieldMapperErrorHandler.java:11)
	at org.sfm.csv.impl.CsvMapperCellConsumer.newCellForSetter(CsvMapperCellConsumer.java:162)
	at org.sfm.csv.impl.CsvMapperCellConsumer.newCell(CsvMapperCellConsumer.java:191)
	at org.sfm.csv.impl.CsvMapperCellConsumer.newCell(CsvMapperCellConsumer.java:177)
	at org.sfm.csv.parser.AbstractCsvCharConsumer.newCell(AbstractCsvCharConsumer.java:101)
	at org.sfm.csv.parser.AbstractCsvCharConsumer.newCellIfNotInQuote(AbstractCsvCharConsumer.java:45)
	at org.sfm.csv.parser.StandardCsvCharConsumer.nextRow(StandardCsvCharConsumer.java:41)
	at org.sfm.csv.CsvReader.parseRow(CsvReader.java:70)
	at org.sfm.csv.impl.CsvMapperIterator.fetch(CsvMapperIterator.java:39)
	at org.sfm.csv.impl.CsvMapperIterator.hasNext(CsvMapperIterator.java:31)
	at TestIssue84$.testDate(ScalaMain.scala:59)
	at TestIssue84$.main(ScalaMain.scala:31)
	at TestIssue84.main(ScalaMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:85)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.sfm.csv.impl.ParsingException: Unparseable date: ""
	at org.sfm.csv.impl.cellreader.DateCellValueReader.read(DateCellValueReader.java:26)
	at org.sfm.csv.impl.cellreader.DateCellValueReader.read(DateCellValueReader.java:11)
	at org.sfm.csv.impl.cellreader.CellSetterImpl.set(CellSetterImpl.java:21)
	at org.sfm.csv.impl.CsvMapperCellConsumer.newCellForSetter(CsvMapperCellConsumer.java:159)
	at org.sfm.csv.impl.CsvMapperCellConsumer.newCell(CsvMapperCellConsumer.java:191)
	at org.sfm.csv.impl.CsvMapperCellConsumer.newCell(CsvMapperCellConsumer.java:177)
	at org.sfm.csv.parser.AbstractCsvCharConsumer.newCell(AbstractCsvCharConsumer.java:101)
	at org.sfm.csv.parser.AbstractCsvCharConsumer.newCellIfNotInQuote(AbstractCsvCharConsumer.java:45)
	at org.sfm.csv.parser.StandardCsvCharConsumer.nextRow(StandardCsvCharConsumer.java:41)
	at org.sfm.csv.CsvReader.parseRow(CsvReader.java:70)
	at org.sfm.csv.impl.CsvMapperIterator.fetch(CsvMapperIterator.java:39)
	at org.sfm.csv.impl.CsvMapperIterator.hasNext(CsvMapperIterator.java:31)
	at TestIssue84$.testDate(ScalaMain.scala:59)
	at TestIssue84$.main(ScalaMain.scala:31)
	at TestIssue84.main(ScalaMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:85)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by arnaudroger** [comment] 2015-01-28 18:08
Thanks for that I'll add a ticket to better report the error, and change the date reader to return null for empty string. Hopefully I'll have that sorted by the end of the week. If you can't wait you can provide your own custom reader but you need to use the csv mapper factory directly.

**Comment by eharik** [comment] 2015-01-28 18:26
Great, thanks!

**Closed** 2015-01-28 20:31 UTC

**Comment by arnaudroger** [comment] 2015-01-29 11:37
I will be published the new version with jodatime and fixes soon, I think though that you probably will have to change the date format used. I added some doc on the wiki

https://github.com/arnaudroger/SimpleFlatMapper/wiki/CsvParser#customised-date-format

tell me if your stuck

**Comment by eharik** [comment] 2015-01-29 14:44
Excellent, thanks.  

Another question on the topic - with jOOQ you can use some wildcarding to specify the columns that should use a custom mapper.  Is there similar support here?  In other words, if I want to define that all columns matching the form `*_date` should use the specified column definition is that possible?

```
CsvMapper<MyObject> mapper = 
    CsvMapperFactory
        .newInstance()
        .addColumnDefinition("*_date", CsvColumnDefinition.dateFormatDefinition("yyyyMMdd"))
        .newMapper(MyObject.class);

**Comment by arnaudroger** [comment] 2015-01-29 14:46
Not at the moment but it would be very difficult or had that or something similar

**Comment by arnaudroger** [comment] 2015-01-29 14:47
The column definition is an case insensitive match right now

**Comment by lukaseder** [comment] 2015-01-29 14:50
@arnaudroger : This looks all very interesting. If you're interested in writing a guest blog post about using jOOQ+SimpleFlatMapper on blog.jooq.org (which is published also on DZone, JavaCodeGeeks, JAXenter and voxxed), let me know. This would certainly get you some additional traction.

**Comment by arnaudroger** [comment] 2015-01-29 14:53
Thanks very much appreciated. I need to write something I have not come around it yet just will keep you posted

**Comment by lukaseder** [comment] 2015-01-29 14:59
Sure, any time you're ready

**Comment by arnaudroger** [comment] 2015-01-31 15:56
@eharik on the *_date column def I added the ticket #89 you would provide a predicate on the key. 
addColumnDefinition((k) -> k.getName().endsWith("_date"), CsvColumnDefinition.dateFormatDefinition("yyyyMMdd")) to do the equivalent.

**Comment by eharik** [comment] 2015-01-31 19:22
very cool!  I'll let you know if I have any issues.

**Comment by arnaudroger** [comment] 2015-01-31 20:01
I will be in 1 4 1 should have it ready tomorrow

**Comment by arnaudroger** [comment] 2015-01-31 21:09
141 is released
